spring:
  datasource:
    url: jdbc:mysql://localhost:3306/timetabler?useSSL=false&serverTimezone=UTC
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: none   # <===== THIS FIXES EVERYTHING
    show-sql: false
    properties:
      hibernate.hbm2ddl.auto: none   # <==== REQUIRED for Hibernate 6

logging:
  level:
    root: INFO
    com.example: DEBUG
    org.optaplanner: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

optaplanner:
  solver:
    termination:
      spent-limit: 180s
      unimproved-spent-limit: 5s
