spring:
  datasource:
    url: jdbc:mysql://localhost:3306/timetable?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver   # ðŸ”¥ THIS WAS MISSING

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate.hbm2ddl.auto: none

logging:
  level:
    root: INFO
    com.example: DEBUG
    org.optaplanner: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

optaplanner:
  solver:
    termination:
      spent-limit: 180s
      unimproved-spent-limit: 5s
